### PR TITLE
[d3] Sphere basis

### PR DESCRIPTION
**Pull request by kburns**
This PR implements S2 operators, tests, and examples. The tests all currently pass except for a couple related to the sine mode for m=0, which is being addressed in the d3-valid branch. Remaining things:

- [x] Add cosine multiplication operator
- [x] Add more tests
- [x] Finalize examples

### CODE REVIEW

**Comment by kburns** [comment]
Probably only need one of barotropic/shallow water examples, but need to understand nonlinear stability, and probably add diffusion, etc.

**Comment by kburns** [comment]
Seems like the instability might just be from using complex numbers. Zeroing the imaginary part each timestep fixes the issue, and it runs as expected (maintains nonlinear solution with slow viscous decay).

**Comment by kburns** [comment]
Decided to keep the shallow water example and add a jet to it, and move the barotropic script to the scratch directory, since its really a scalar problem that doesn't require vector fields.

I think this is pretty much ready to go now.  Could always use more tests, of course, but maybe good enough for now?

**Comment by bpbrown** [comment]
Looks good to me; we can add other tests and examples later, so I'd say
let's get this merged!

**Pull request merged**
